Separate check scripts to their own repository (#567)
* Remove scripts

* Update workflows to use checks repo

* Add explanation about naming of base branch

This only concerns private tests with PRs created against a base branch in
another non-official repo.

* Fix checkout paths

* Move TESTING to a less confusing location

diff --git a/.github/workflows/diff-release.yml b/.github/workflows/diff-release.yml
--- a/.github/workflows/diff-release.yml
+++ b/.github/workflows/diff-release.yml
@@ -1,7 +1,13 @@
+# Please read the TESTING file before modifying this file
+
 # Show differences between the submitted manifest and the previous
 # release of the same crate, to enable easier catching of problems
 
 name: Diff release
+
+env:
+  CHECKS_ORG: alire-project
+  CHECKS_REPO: alire-index-checks
 
 on:
   pull_request:
@@ -22,6 +28,13 @@ jobs:
         # Needed to be able to diff and obtain changed files. Furthermore, we
         # need the full history or else grafted partial branches confuse the
         # changed files detector
+
+    - name: Check out alire-index-checks
+      uses: actions/checkout@v3
+      with:
+        repository: ${{env.CHECKS_ORG}}/${{env.CHECKS_REPO}}
+        ref: ${{github.base_ref}}
+        path: ${{env.CHECKS_REPO}}
 
     - name: Set up stable `alr`
       if: contains(github.base_ref, 'stable-')
@@ -49,5 +62,5 @@ jobs:
         branch: master
 
     - name: Diff releases
-      run: scripts/diff-release.sh || true # No deal breaker if failed
+      run: ${{env.CHECKS_REPO}}/scripts/diff-release.sh || true # No deal breaker if failed
       shell: bash
